# Generated by Django 4.2.7 on 2024-03-04 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('action', models.TextField(verbose_name='действие привычки')),
                ('place', models.CharField(max_length=150, verbose_name='место выполнения')),
                ('lead_time', models.DateTimeField(verbose_name='время выполнения')),
                ('sign_pleasant_habit', models.BooleanField(verbose_name='признак приятности привычки')),
                ('period', models.CharField(choices=[('weekly', 'Раз в неделю'), ('daily', 'Каждый день'), ('in_one_day', 'через день')], max_length=100, verbose_name='периодичность выполнения')),
                ('reward', models.CharField(max_length=250, verbose_name='Вознаграждение')),
                ('time_completed', models.DateTimeField(default=datetime.timedelta(seconds=120), verbose_name='время на выполнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
