# Generated by Django 4.2.7 on 2024-03-12 16:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('action', models.TextField(verbose_name='Действие привычки')),
                ('place', models.CharField(max_length=150, verbose_name='Место выполнения')),
                ('sign_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятности привычки')),
                ('period', models.DurationField(default=datetime.timedelta(days=1), verbose_name='Периодичность выполнения')),
                ('reward', models.CharField(blank=True, max_length=250, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('next_dispatch_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='время следующей отправки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
