# Generated by Django 4.2.7 on 2024-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='sign_pleasant_habit',
            field=models.BooleanField(default=False, verbose_name='признак приятности привычки'),
        ),
    ]
