# Generated by Django 4.2.7 on 2024-03-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_sign_pleasant_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(default='00:02:00', verbose_name='Время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.TextField(verbose_name='Действие привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='lead_time',
            field=models.DateTimeField(verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('weekly', 'Раз в неделю'), ('daily', 'Каждый день'), ('in_one_day', 'Через день')], default='daily', max_length=100, verbose_name='Периодичность выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=150, verbose_name='Место выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=250, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='sign_pleasant_habit',
            field=models.BooleanField(default=False, verbose_name='Признак приятности привычки'),
        ),
    ]
