# Generated by Django 4.2.7 on 2024-03-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_remove_habit_time_completed_habit_related_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.IntegerField(default=1, verbose_name='Периодичность выполнения'),
        ),
    ]
