# Generated by Django 4.2.7 on 2024-03-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='телеграм ID'),
        ),
    ]
