# Generated by Django 4.2.7 on 2024-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_habit_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Признак публичности'),
        ),
    ]
