# Generated by Django 4.2.7 on 2024-03-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_habit_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='telegram_id',
            new_name='chat_id',
        ),
    ]
