# Generated by Django 4.2.7 on 2024-03-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_rename_telegram_id_habit_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='lead_time',
        ),
    ]
