# Generated by Django 4.2.7 on 2024-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0008_remove_habit_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='next_dispatch_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='время следующей отправки'),
        ),
    ]
