# Generated by Django 4.2.7 on 2024-03-10 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_habit_next_dispatch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение'),
        ),
    ]
