# Generated by Django 4.2.7 on 2024-03-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0010_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='chat_id',
        ),
    ]
